<a href="https://colab.research.google.com/github/JayeshSandhikar/CloudyML_Assignments_Solved_Jayesh/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [3]:
s = np.array(5)

In [6]:
s.dtype

dtype('int64')

In [7]:
print

<function print>

In [8]:
np.ndim(s)

0

In [16]:
a = [2,5,3,8,9,6,8,5,88,5,5,5,8,5,5]

In [12]:

a

[2, 5, 3, 8, 9, 6, 8, 5, 88, 5, 5, 5, 8, 5, 5]

In [13]:
 np.array(a)

array([ 2,  5,  3,  8,  9,  6,  8,  5, 88,  5,  5,  5,  8,  5,  5])

In [15]:
np.ndim(a)

1

In [17]:
v = [[1,3,5,4],[8,9,7,8]]

In [19]:
b = np.array(v)

In [20]:
b

array([[1, 3, 5, 4],
       [8, 9, 7, 8]])

In [21]:
np.ndim(b)

2

In [39]:
m = [[[5,5,5,],[999,999,999],[777,777,777,],[855,855,85]],[[978,254,666],[214,548,789],[5895,57895,224789654],[888,888,8]]]

In [37]:
np.array(m)

array([[[        5,         5,         5],
        [      999,       999,       999],
        [      777,       777,       777],
        [      855,       855,        85]],

       [[      978,       254,       666],
        [      214,       548,       789],
        [     5895,     57895, 224789654],
        [      888,       888,         8]]])

In [38]:
np.ndim(m)

3